name: datawarehouse_trigger

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
      - develop
    tags:
      - datawarehouse

  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
      - published

jobs:
  Slack_ping:
    runs-on: ubuntu-latest
    steps:
      - name: List Files After Checkout
        run: |
          echo " ********************************************** List of actions **********************************************"
          echo $GITHUB_SHA 
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          pwd
          ls -a
          git clone git@github:$GITHUB_REPOSITORY
          git checkout $GITHUB_SHA
          sudo apt-get install tree
          echo " ********************************************** tree **********************************************"
          tree
      - name: Slack_ping
        run: |
          echo " ********************************************** Curling **********************************************"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"DataWareHouse_Deploy triggered"}' https://hooks.slack.com/services/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
          
      #- name: Moving build to artifacts directory
      #  run: ./scripts/moveFiles.sh
