name: repo_dispatch
on: 
  repository_dispatch:
    types: [build]

  pull_request:
    types: [closed, assigned, opened, reopened]
jobs:
  slack-steps:
    runs-on: ubuntu-latest
    steps:

      - name: send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Hello slack"
