name: API_repo_dispatch
on:
  repository_dispatch:
   types: [build]
   
  push:
    branches:
      - feature
      - develop
  #pull_request:
  #  types: [closed, assigned, opened, reopened]

jobs:
  slack-steps:
    runs-on: ubuntu-latest
    steps:
      - name: send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          # SLACK_MESSAGE: "${{ github.event.client_payload.SLK_MSG }}"
          SLACK_MESSAGE: "Test Develop failed"
      - name: slack Files After Checkout
        run: |
          pwd
          ls -a
          echo " ********************************************** List of actions **********************************************"
  payload:
    runs-on: ubuntu-latest
    steps:  
      - name: slack API Msg
        run: |
          pwd
          ls -a
          echo " ********************************************** List of actions **********************************************"
          echo $GITHUB_SHA 
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.event.client_payload.SLK_MSG }}"