  
name: Shell Commands

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Python Commands
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-github-action:
    runs-on: ubuntu-latest
    stpes:
      - name: Simple JS Action
        id: greet
        uses: actions/javascript-action@v1
        with: 
          who-to-greet: Surendra
      - name: Logs TimeStamp of who-to-greet
        run: echo "${{ steps.greet.outputs.time }}"
            